# Generated by Django 3.2.3 on 2021-06-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
